name: CI

# You want to run the tests on every push, and for pull requests.
on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Environment variables during project setup and test run.
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: ""
      ADMIN_PREFIX: app
      IS_LIVE: true
      TRIAL_DAYS: 14
      STRIPE_KEY: pk_test_1OAismyoTlSyyWFiqgQ3vPgv00KnCaqv19
      STRIPE_SECRET: sk_test_O3qRBFQ4coAB7Hzl2bFYzGM700BGbW7RpY
      STRIPE_WEBHOOK_SECRET: whsec_2ec36b8f68905c71d2f14a3dc8ee5497932f57cf8a6fb75341a7166ffffb21ff
      STRIPE_MONTHLY: price_1NbOhULiL14otffRI9TPcHo4
      STRIPE_ANNUALLY: price_1NbOhULiL14otffRvPO2pt3b

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Vite
        run: npm run build

      - name: Migrate DB
        run: php artisan migrate --seed

      - name: Generate key
        run: php artisan key:generate

      - name: Set storage link
        run: php artisan storage:link

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: PINT
        run: ./vendor/bin/pint --test

      - name: Execute tests (Unit and Feature tests) via Pest
        run: vendor/bin/pest --parallel
